import img1 from "../../public/img/pervij.png";
import img2 from "../../public/img/russia_1.png"
import { StaticImageData } from "next/image";
// Тип данных для одного канала
export interface Channel {
    id:number;
  name: string;
  img: StaticImageData; // если Next.js Image
  bgColor: string;
  href: string;
  url:string;
}

// Массив с типизацией
export const channelInfo: Channel[] = [
  {id:1,
    name: "Uzbekiston",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:2,
    name: "Yoslar",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:3,
    name: "Toshkent",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:4,
    name: "Sport",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:5,
    name: "Madaniyat va Marifat",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:6,
    name: "Mahalla",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:7,
    name: "Futbol Tv",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:8,
    name: "Dunyo Bo`ylab",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:9,
    name: "Bolajon",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:10,
    name: "Navo",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:11,
    name: "Kinoteatr",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:12,
    name: "Uzbekiston 24",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:13,
    name: "Taraqqiyot",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:14,
    name: "Uzreport TV",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:15,
    name: "MY5",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:16,
    name: "Milly",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:17,
    name: "ZorTV",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:18,
    name: "Sevimli",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:19,
    name: "Aqlvoy",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:20,
    name: "Dasturxon TV",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:21,
    name: "FTV",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:22,
    name: "MuzTV UZ",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:23,
    name: "Biz TV",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:24,
    name: "Uzbekiston Tarixi HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:25,
    name: "Kinoteatr HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:26,
    name: "ZorTV HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:27,
    name: "Sevimli HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:28,
    name: "Sport UZ HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:29,
    name: "EuroSport 1",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:30,
    name: "KHL",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:31,
    name: "Viasat Sport",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:32,
    name: "MMA-TV.COM",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:33,
    name: "Setanta Sports 1 HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:34,
    name: "Setanta Sports 2 HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:35,
    name: "Trace Sport Stars HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:36,
    name: "1HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:37,
    name: "Biz Music HD UZ",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:38,
    name: "Bridge TV Classic",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:39,
    name: "Globus Music",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:40,
    name: "Ru TV",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:41,
    name: "MuzTV",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:42,
    name: "Avia",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:43,
    name: "TNT Music",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:44,
    name: "СТВ  Музыка HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:45,
    name: "Ля-Минор",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:46,
    name: "Музыка Первого",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:47,
    name: "TRT Muzik",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:48,
    name: "Bridge TV Classic",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:49,
    name: "Globus Music",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:50,
    name: "Ru TV",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:51,
    name: "Biz Cinema UZ",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:52,
    name: "TV1000",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:53,
    name: "TV1000 Action HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:54,
    name: "TV1000 Русское Кино",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:55,
    name: "Дорама",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:56,
    name: "Дом Кино",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:57,
    name: "Кинопоказ",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:58,
    name: "Наше Новое Кино",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:59,
    name: "Родное Кино",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:60,
    name: "Кинохит",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:61,
    name: "Киносерия",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:62,
    name: "Киносемья",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:63,
    name: "Киносвидание",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:64,
    name: "Киномикс",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:65,
    name: "Кинокомедия",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:66,
    name: "Индийское Кино",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:67,
    name: "Домашний",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:68,
    name: "Арсенал HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:69,
    name: "Bollywood",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:70,
    name: "Родное Кино",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:71,
    name: "Кинохит",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:72,
    name: "Киносерия",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:73,
    name: "Первый канал",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:74,
    name: "НТВ-Мир",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:75,
    name: "НТВ",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:76,
    name: "Россия К",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:77,
    name: "Россия 24",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:78,
    name: "Россия 1",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:79,
    name: "Техно 24",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:80,
    name: "Телепутешествия",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:81,
    name: "Приключения",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:82,
    name: "Первый Космический",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:83,
    name: "Охотник и Рыболов HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:84,
    name: "Охотник и Рыболов",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:85,
    name: "Загородный",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:86,
    name: "Наша Сибирь",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:87,
    name: "Animal Planet",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:88,
    name: "Наука",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:89,
    name: "Моя Планета",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:90,
    name: "Живая Природа HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:91,
    name: "Глазами Туриста",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:92,
    name: "Вопросы и Ответы",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:93,
    name: "В Мире Животных",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:94,
    name: "Viasat Nature",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:95,
    name: "Viasat History",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:96,
    name: "Viasat Explore",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:97,
    name: "NAT GEO WILD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:98,
    name: "National Geographic",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:99,
    name: "Insight TV HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:100,
    name: "HD Life",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:101,
    name: "История",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:102,
    name: "Discovery Science",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:103,
    name: "Discovery Channel",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:104,
    name: "Живая Планета",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:105,
    name: "Усадьба",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:106,
    name: "Точка Отрыва",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:107,
    name: "ТВЦ",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:108,
    name: "ТВ3",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:109,
    name: "Сарафан",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:110,
    name: "Ретро",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:111,
    name: "РБК",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:112,
    name: "Мир 24",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:113,
    name: "Мир",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:114,
    name: "Кухня ТВ",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:115,
    name: "Капитан Фантастика HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:116,
    name: "Казахстан 24",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:117,
    name: "Зоопарк",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:118,
    name: "Здоровое ТВ",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:119,
    name: "Звезда",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:120,
    name: "Живи Активно HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:121,
    name: "Живи",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:122,
    name: "Драйв",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:123,
    name: "Домашние Животные",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:124,
    name: "Авто Плюс",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:125,
    name: "Авто 24",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:126,
    name: "Turan TV",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:127,
    name: "TRT Haber",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:128,
    name: "TRT Avaz",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:129,
    name: "Ruxsor TV UZ",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:130,
    name: "Renessans TV UZ",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:131,
    name: "Qasaqstan",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:132,
    name: "Nurafshon TV UZ",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:133,
    name: "Ntv UZ",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:134,
    name: "Fuel TV",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:135,
    name: "NHK World Japan",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:136,
    name: "Myzen HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:137,
    name: "Museum HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:138,
    name: "Mezzo Life HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:139,
    name: "Lux TV",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:140,
    name: "KBS WORLD",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:141,
    name: "Istiqlol TV",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:142,
    name: "France 24",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:143,
    name: "Fox News",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:144,
    name: "Fashion TV",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:145,
    name: "Euronews",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:146,
    name: "English Club",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:147,
    name: "CNN",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:148,
    name: "CGTN",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:149,
    name: "Bloomberg",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:150,
    name: "BBC WORLD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:151,
    name: "8 Канал",
    img: img1,
    bgColor: "gray",
    href: "asd",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:152,
    name: "365 Дней HD",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:153,
    name: "Duck TV",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:154,
    name: "Детский Мир",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:155,
    name: "Рыжий",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:156,
    name: "Мама",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:157,
    name: "Уникум",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:158,
    name: "СТС Kids",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:159,
    name: "Карусель",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:160,
    name: "Da Vinci",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:161,
    name: "Смайлик ТВ",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:162,
    name: "Мультиландия",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:163,
    name: "Мульт",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:164,
    name: "В Гостях У Сказки",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:165,
    name: "Tiji",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
  {id:166,
    name: "Gulli Girl",
    img: img2,
    bgColor: "black",
    href: "asdsad",
    url:"https://stream2.cinerama.uz/1008/tracks-v1a1/mono.m3u8",
  },
];